version: "3.9"
services:
  image-caption-viewer:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./images:/app/static
    environment:
      - SERVER_URL=<Enter URL of the server> # Ask the instructor for the URL
