openapi: 3.0.0
info:
  title: Image Caption Server
  version: v1
paths:
  /server:
    post:
      summary: Generate a caption for an image
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                image:
                  type: string
                  description: Base64 encoded image data
                  required: true
                prompt:
                  type: string
                  description: Prompt for the caption generation
                  required: true
      responses:
        '200':
          description: Successful caption generation
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
                    description: The generated caption
        '400':
          description: Error processing image
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
        '405':
          description: Only POST requests are allowed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
